### ISSUE TITLE
Could not import circuit: Unable to cast Python instance to C++ type

### ISSUE THREAD

**Issue by DiracMG3** [iic-jku/qmap#13]
Hi there~
I want to use JKQ QMAP in Python to map a qiskit QuantumCircuit to a real quantum device, but have some trouble with it. 
I constructed a Qiskit QuantumCircuit object added some gates on it(with parameters) :
```
from qiskit import QuantumCircuit
circ = QuantumCircuit(n,n)
circ.append(...)
```

I checked my circuit and plotted it, it is valid. Then following the instruction I wrote my code :

```
qmap.compile(circ, 'IBM_QX5', method=qmap.Method.heuristic)
```

now I am getting the error :
**'Could not import circuit: Unable to cast Python instance to C++ type (compile in debug mode for details)'**

I don't know what is wrong. Could you please help me to solve it? Thanks a lot!

**Comment by DiracMG3** [comment]
I solved the problem. The gates of circuit should not have free parameters, when I fixed the parameters, it works.

**Comment by burgholzer** [comment]
Sorry for not getting back to you earlier. Glad you were able to fix the problem. Indeed, importing parametrised circuits from Qiskit is not possible at the moment. 
I guess you are trying to map some VQE/QAOA circuit or such, right?

At the moment, just binding the parameters seems to be the only workaround. However, we might consider adding support for parametrised gates in the future.

**Comment by DiracMG3** [comment]
Yes, I am trying to map a QAOA circuit. But thanks for your reply anyhow😄.
