### ISSUE TITLE
Qmap Heuristic Layering strategy

### ISSUE THREAD

**Issue by IshaniGowaikar** [iic-jku/qmap#2]
Thank you for this work, it is very interesting and I found it quite helpful. 
I had a question about changing the layering strategy in heuristic mapper. I noticed in the output, the gates are not grouped to form a layer, instead each gate is considered as its own layer. Is it possible to change the layering strategy? 

I wanted to see if I could somehow change the root node of the A* algorithm, to get more than one mapping possibilities at each layer.

Any help would be greatly appreciated. Thanks in advance.

**Comment by burgholzer** [comment]
Thanks for your interest in our work. At the moment, this is not supported for the heuristic mapper.
I will look into it and get back to you once I know more!

**Comment by burgholzer** [comment]
Hi there,

I just pushed a commit that experimentally enables the selection of a layering strategy in the heuristic mapper.
The corresponding command line argument is "--layering". Grouping of (disjoint) gates into a layer is supported using "--layering disjoint". Note, that grouping gates in such a fashion will in general yield worse results as compared to considering gates individually.

If you want to define your own layering/partitioning schemes, the following steps are necessary:
- In `MappingSettings.hpp` provide a new member to the `LayeringStrategy` enum class and a corresponding entry in the `toString` method.
- In `Mapper.cpp` augment the `createLayers` function for the new strategy
- Add the new strategy to the command line tool in `heuristic_app.cpp` by setting the `ms.layeringStrategy` based on the received string.

If you implement some new strategies, feel free to submit a pull request 👍🏼 

I hope this helps. In case of questions, don't hesitate to ask.

**Comment by IshaniGowaikar** [comment]
Thank you so much for your help. I really appreciate you getting back to me
so quickly. I will try doing this right away and if I manage to come up
with a new strategy, I'll definitely submit a pull request.
Thank you again, and I really appreciate this.


Thanks and best regards,
Ishani Gowaikar

**Comment by burgholzer** [comment]
Closing this for now. Feel free to re-open if you have further questions!

**Comment by IshaniGowaikar** [comment]
Yes, thank you so much for your help.
